# Example configuration for the Booru Client.
# Copy this file to `config.toml` or `config.yaml` and adjust as needed.

[default]
# Directory where downloads and metadata are saved by default.
download_dir = "./downloads"
# Cache directory relative to the project root.
cache_dir = "./cache"
# How many seconds search results stay fresh before hitting the API again.
cache_ttl = 900

[boorus.danbooru]
base_url = "https://danbooru.donmai.us"
search_endpoint = "/posts.json"
post_endpoint = "/posts/{id}.json"
rate_limit_per_sec = 1.0
max_page_size = 20
# Optional API key + login can go here for higher limits.
# api_key = "your-api-key"
# user = "username"

[boorus.gelbooru]
base_url = "https://gelbooru.com"
search_endpoint = "/index.php?page=dapi&s=post&q=index&json=1"
post_endpoint = "/index.php?page=dapi&s=post&q=index&json=1&id={id}"
rate_limit_per_sec = 0.5
max_page_size = 100

[boorus.safebooru]
base_url = "https://safebooru.org"
search_endpoint = "/index.php?page=dapi&s=post&q=index&json=1"
post_endpoint = "/index.php?page=dapi&s=post&q=index&json=1&id={id}"
rate_limit_per_sec = 0.5
max_page_size = 40
