name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[developer,practical,constructive_solid_geometry]

      - name: Run test suite
        env:
          IMAGEBOARD_DATA_DIR: ${{ runner.temp }}/imageboard-data
          IMAGEBOARD_SECRET_KEY: testing-secret
          IMAGEBOARD_ADMIN_PASSWORD: letmein
        run: pytest
